version: '3'
services:
  python-ip-manager:
    build: .
    ports:
      - "8027:8027"
    restart: unless-stopped
    volumes:
      - /mnt/nfs/shared/lists/blacklist.txt:/app/blacklist.txt
      - /mnt/nfs/shared/lists/whitelist.txt:/app/whitelist.txt
