version: '3'
services:
  ip-manager:
    image: ip-manager:1
    ports:
      - "8027:8027"
    restart: unless-stopped
    volumes:
      - /var/www/html/blacklist.txt:/app/blacklist.txt
      - /var/www/html/whitelist.txt:/app/whitelist.txt
