version: '3'
services:
  ipmanager:
    build: .
    ports:
      - "8027:8027"
    restart: unless-stopped
    volumes:
      - /var/www/html/blacklist.txt:/app/blacklist.txt
      - /var/www/html/blacklist.txt:/app/whitelist.txt
